### ISSUE TITLE
Windows版本修改哪个配置文件呢？

### ISSUE THREAD

**Issue by JsHuang** [timothyzhw/evernote-markdown-vue#1]
Windows版本修改哪个配置文件呢？mac版本index.html文件内容是什么样的？

**Comment by nicesome** [comment]
楼上同问，Windows 配置修改什么呢？

**Comment by chendifan** [comment]
同问。。。

**Comment by xyzhou-1** [comment]
https://github.com/hyboxu/evernote-markdown-win-theme

**Comment by bearcai** [comment]
> https://github.com/hyboxu/evernote-markdown-win-theme

大哥，你是我亲大哥啊
